# -*- coding: utf-8 -*-
"""四維宏觀動態防護系統.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVzse7mUdWvQ487s_zYJPLpKvqosgcFi
"""

import streamlit as st
import yfinance as yf
import pandas_datareader.data as web
import pandas as pd
from datetime import datetime, timedelta
import time

# 1. 網頁基本設定 (Page Configuration)
st.set_page_config(page_title="AI 財經防護儀表板", layout="wide")
st.title("四維宏觀與動態資產防護儀表板 (4D Macro & DAA Dashboard)")
st.markdown("---")

# 2. 建立三大模組頁籤 (Tabs)
tab1, tab2, tab3 = st.tabs(["一、四維防護系統 (避險)", "二、長期估值濾網 (長線)", "三、動態提領試算 (退休)"])

end_date = datetime.now()
start_date_1y = end_date - timedelta(days=365)
start_date_18m = end_date - timedelta(days=540)

# ==========================================
# 頁籤一：四維防護系統 (4D Protection System)
# ==========================================
with tab1:
    st.subheader("四維緊急煞車與三維動能檢驗")
    if st.button("啟動檢驗 (Run Analysis)"):
        with st.spinner("正在從 FRED 與 Yahoo Finance 抓取即時數據..."):
            try:
                # 抓取信用利差 (HY OAS)
                hy_spread = web.DataReader('BAMLH0A0HYM2', 'fred', start_date_1y, end_date).dropna()
                current_spread = hy_spread.iloc[-1].values[0]
                spread_1m_ago = hy_spread.iloc[-21].values[0]
                spread_change = current_spread - spread_1m_ago

                # 抓取 SPY 均線
                spy_data = yf.download('SPY', start=start_date_1y, end=end_date, progress=False)['Adj Close']
                if isinstance(spy_data, pd.DataFrame):
                    spy_data = spy_data.squeeze()
                spy_200sma = spy_data.rolling(window=200).mean().iloc[-1]
                spy_current = spy_data.iloc[-1]

                # 畫面排版：建立左右兩欄顯示數據
                col1, col2 = st.columns(2)
                col1.metric("高收益債信用利差 (HY OAS)", f"{current_spread:.2f}%", f"{spread_change:+.2f}% (月變動)", delta_color="inverse")
                col2.metric("標普500 (SPY) 現價 vs 200日均線", f"{spy_current:.2f}", f"均線: {spy_200sma:.2f}")

                # 邏輯判定與警示
                if current_spread > 5.0 or spread_change > 1.0:
                    st.error("🚨 **警報觸發！實體經濟違約風險過高，啟動強制防禦。**\n\n**決策**：清空所有股票，100% 轉入 BIL (短期國庫券)。企業主請凍結資本支出！")
                elif spy_current > spy_200sma:
                    st.success("✅ **多頭確認：市場流動性與經濟成長健康。**\n\n**決策**：啟動攻擊配置，尋找相對動能強勢板塊。")
                else:
                    st.warning("⚠️ **空頭確認：大盤跌破長期均線，資金動能衰退。**\n\n**決策**：防禦配置，資金轉入 IEI (中天期公債) 與 BIL (短期國庫券)。")
            except Exception as e:
                st.error(f"資料抓取失敗: {e}")

# ==========================================
# 頁籤二：長期估值濾網 (Long-term Valuation Filter)
# ==========================================
with tab2:
    st.subheader("20法則 (Rule of 20) 大盤水位評估")
    if st.button("計算估值 (Calculate Valuation)"):
        with st.spinner("正在計算通膨與本益比數據..."):
            try:
                # 抓取 CPI
                cpi_data = web.DataReader('CPIAUCSL', 'fred', start_date_18m, end_date).dropna()
                cpi_current = cpi_data.iloc[-1].values[0]
                cpi_year_ago = cpi_data.iloc[-13].values[0]
                cpi_yoy = ((cpi_current - cpi_year_ago) / cpi_year_ago) * 100

                # 抓取 SPY PE Ratio
                spy = yf.Ticker("SPY")
                pe_ratio = spy.info.get('trailingPE', 0)

                if pe_ratio > 0:
                    rule_of_20 = pe_ratio + cpi_yoy
                    col1, col2, col3 = st.columns(3)
                    col1.metric("標普500 本益比 (P/E)", f"{pe_ratio:.2f}")
                    col2.metric("核心通膨年增率 (CPI YoY)", f"{cpi_yoy:.2f}%")
                    col3.metric("20法則數值", f"{rule_of_20:.2f}")

                    if rule_of_20 < 20:
                        st.info("💡 **估值狀態：【低估 (Undervalued)】**\n\n建議：長線便宜區間，可加速定期定額佈局。")
                    else:
                        st.warning("⚠️ **估值狀態：【高估 (Overvalued)】**\n\n建議：大盤不便宜，請勿單筆重壓，保留現金彈性。")
                else:
                    st.error("目前無法取得本益比數據。")
            except Exception as e:
                st.error(f"資料抓取失敗: {e}")

# ==========================================
# 頁籤三：動態安全提領率試算 (Dynamic SWR)
# ==========================================
with tab3:
    st.subheader("退休金動態提領計算機 (Retirement Withdrawal Calculator)")

    col1, col2 = st.columns(2)
    with col1:
        portfolio_value = st.number_input("請輸入預估退休金總額 (萬元):", min_value=100, value=1000, step=100)
        inflation_rate = st.number_input("預估年度通膨率 (%):", min_value=0.0, value=2.0, step=0.1) / 100
    with col2:
        market_status = st.radio("目前系統判定的大盤狀態為：", ("多頭 (Bull Market)", "空頭 (Bear Market)"))

    if st.button("試算本年度提領金 (Calculate SWR)"):
        if market_status == "多頭 (Bull Market)":
            base_swr = 0.045
            withdrawal = portfolio_value * base_swr * (1 + inflation_rate)
            st.success(f"📈 **建議提領率：{base_swr*100}% + 通膨調整**")
            st.info(f"💰 **本年度可安全提領：{withdrawal:.2f} 萬元**\n\n說明：市場擴張期，可安心維持購買力 (Purchasing power)。")
        else:
            base_swr = 0.03
            withdrawal = portfolio_value * base_swr
            st.error(f"📉 **建議提領率：{base_swr*100}% (凍結通膨調整)**")
            st.warning(f"💰 **本年度可安全提領：{withdrawal:.2f} 萬元**\n\n說明：市場空頭期，請縮減開支，保護核心本金 (Principal)。")